---
count: 6
default:
  restart: 0
  wait: 1
editor:
  files:
    base:
      - lib/App/PasswdMgr.pm
      - lib/App/PasswdMgr/Base.pm
    actions:
      - lib/App/PasswdMgr/List.pm
      - lib/App/PasswdMgr/Password.pm
name: passwdmgr
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
  2:
    edit: base
  3:
    edit: actions
  4:
    restart: 1
    edit: bin
