=begin html

<a href="https://travis-ci.org/ivanwills/App-PasswdMgr"><img src="https://travis-ci.org/ivanwills/App-PasswdMgr.png" alt="App-PasswdMgr"></a>
<a href="https://coveralls.io/r/ivanwills/App-PasswdMgr?branch=master"><img src="https://coveralls.io/repos/ivanwills/App-PasswdMgr/badge.svg?branch=master" alt="Coverage Status" /></a>

=head1 App-PasswdMgr

This package provides a command line tool to manage passwords in a (untested)
secure fashion. It is inspired by the programs like KeyPassX but is managed
on the command line.

=head1 INSTALLATION

To install this module, run the following commands:

    perl Build.PL
    ./Build
    ./Build test
    ./Build install

=head1 SUPPORT AND DOCUMENTATION

After installing, you can find documentation for this module with the
perldoc command.

    perldoc App::PasswdMgr

You can also look for information at:

    RT, CPAN's request tracker
        http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-PasswdMgr

    AnnoCPAN, Annotated CPAN documentation
        http://annocpan.org/dist/App-PasswdMgr

    CPAN Ratings
        http://cpanratings.perl.org/d/App-PasswdMgr

    Search CPAN
        http://search.cpan.org/dist/App-PasswdMgr/

    Source Code
        git://github.com/ivanwills/App-PasswdMgr.git

=head1 COPYRIGHT AND LICENCE

Copyright (C) 2016 Ivan Wills

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.

=cut
